### PR TITLE
rio color and rio atmos

### LINKED ISSUE #5: Channel selectors
@virginiayung and I want a syntax and mechanism for `rio color` to apply given operations only to selected channels. For comparison, ImageMagick’s `convert` works like this:

`convert input.tif -channel G -gamma 1.5 -channel B -gamma 0.5 -sigmoidal-contrast 3,50% -channel RGB output.tif`

Which is something like this in pseudocode:

```
G = gamma(G, 1.5);
B = gamma(B, 0.5);
B = sigmoid(B, 3, 50);
write([R, G, B], output.tif);
```

Implicitly, R is passed through. It amounts to a simple system for creating blocks of operations.

I don’t love the `convert` syntax (for example, it’s easy to forget to switch back to RGB at the end) but it seems to mostly work. I wonder about something maybe more like this:

`rio color 'G(gamma 1.6) B(gamma 0.5, sigmoid 3 50)' input.tif output.tif`

Or maybe full s-expressions, or…?

### LINKED ISSUE #6: Saturation operator
One of the `convert` flags we want to replace is the second argument to `-modulate`, which adjusts saturation. _(Pulled out of #5.)_ Braindumping some options, in order of increasing hackiness:

1. The conceptually straightest path here is to convert RGB to a radial colorspace that has a dedicated saturation channel, multiply that channel, and convert it back. Our default radial colorspace is LCH, because it combines [a nicely grounded definition](https://en.wikipedia.org/wiki/Lab_color_space) with a good approximation of perceptual uniformity. Unfortunately, the conversion is relatively complex and resource-hungry: `skimage`, for example, goes RGB &rarr; Lab &rarr; LCH and back.

2. We could use HSV, which has a simpler definition.\* The :-1: I see is setting a precedent of using HSV, which isn’t our best practice. I think it’s wiser to keep `rio color` in a “gold standard” role instead of a “workable approximation” role – for that, you might as well write your own functions. \*Though _possibly_ not faster, given that it has a 6-part `case`, as opposed to the trig functions of the LCH route. I don’t have good intuition about numpy optimization.

3. We could work out an equivalent (ish) saturation operator that works directly on RGB pixels. I see this as even more of a hack: by the time it was well defined, it’d be doing 80% of the work of converting to and from a radial colorspace anyway. On the :+1:, it would probably be very fast and do a fairly good job of matching any other saturation operator.

How do you see this, @perrygeo?

### PR DESCRIPTION
**Pull request by perrygeo**
As discussed in #5, we need a low level tool to apply color corrections (`rio color`) in addition to a high-level atmospheric correction command (`rio atmos`). 

Related to #4 
Resolves #5 
Also resolves #6 - adding a saturation operator in LCH color space

See [the README](https://github.com/mapbox/rio-color/blob/color-vs-atmos/README.md) in this branch for usage.

**This is ready but for the travis thing**

## TODO
- [x] compare results to imagemagick `convert`
- [x] benchmarking
- [x] document examples
- [x] unit tests for CLI and Python API (100% coverage!)
- [x] clean up python api into modules, document in readme
- [x] travis

### CODE REVIEW

**Comment by perrygeo** [comment]
Example:

```
$ rio stack ~/projects/sentinel2/B0{4,3,2}.jp2 rgb.tif
$ rio color -d uint8 -j 6 rgb.tif test.tif \
    "gamma 3 1.85" "gamma 1,2 1.95" "sigmoidal 1,2,3 35 0.13" "saturation 115"
```

screen shot 2016-02-17 at 12 18 47 pm

**Comment by perrygeo** [comment]
Quick benchmarks against `convert`, using the above command w/ and w/out saturation

| command                  | time | maxmem |
|--------------------------|------|--------|
| rio color                | 16s  | 125    |
| rio color -j 8           | 5s   | 265   |
| rio color saturation     | 86s  | 120    |
| rio color -j8 saturation | 20s  | 260   |
| convert                  | 5.5s | 1600   |
| convert saturation       | 13s  | 1580   |

Some conclusions:
* Rio color in single-core mode is 3x slower than covert
* Rio color in multi-core mode is roughly equivalent runtimes on an 8-core machine
* saturation, because it involves going between colorspaces, seems inherently slower in both
* rio color's saturation is an additional 2x slower than convert
* Memory usage is dramatically lower using rio color.
* rio color is doing more work (integer type handling, copying geotransform, retaining the block structure of the original image) - convert needs post-processing in most spatial applications which adds complexity and eats into it's advantages.

So: `rio color` - slightly slower but a better interface, mutlicore, much lower memory usage and we can improve it going forward.

**Comment by perrygeo** [comment]
Visual comparison of results between equivalent commands. They look like the exact same image to my eyes...

```
convert -channel B -gamma 1.85 -channel RG -gamma 1.95 \
    -channel RGB -sigmoidal-contrast 35,13% -modulate 100,115 \
    rgb.tif out_convert.tif
```
screen shot 2016-02-18 at 5 48 22 am

```
rio color -d uint8 -j 8 rgb8.tif ~/Desktop/out_rio_sat8.tif \
    "gamma 3 1.85" "gamma 1,2 1.95" "sigmoidal 1,2,3 35 0.13" "saturation 115"
```
screen shot 2016-02-18 at 5 48 36 am

**Comment by perrygeo** [comment]
@celoyd tests passing on travis, this is good to go pending review.

**Comment by celoyd** [comment]
:+1: Looks good to me, @perrygeo!

Per chat, there are some questions about how to handle `photometric=rgb`, but I think what’s here is working and coherent as it stands, and is ready to board the Mergeville bus.

- [x] Browsed code, lightly watering and pruning the help strings as I passed by.
- [x] Eyeball-confirmed expected outputs on a range of images I had lying around. Typical RMSE of channel means against `convert` results is about 0.5 for common operations on `uint8` images. This is possibly worth revisiting to understand better later.
- [x] Confirmed good behavior with some pathological inputs like huge gamma values.

**Comment by perrygeo** [comment]
:ship:

**Pull request merged**
